---
sudo: required
language: python
python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install molecule
  - pip install docker

script:
  - molecule --version
  - ansible --version
  - docker --version
  - cd nomad
  - molecule test
