---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

template: &nomad-agent
  environment:
    container: docker
  image: ${JOB_DOCKER_IMAGE:-'centos:7'}
  privileged: true
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  tmpfs:
  - /tmp
  - /run
  command: "${JOB_DOCKER_COMMAND:-'/usr/sbin/init'}"
  tty: true

platforms:
- name: mlc-server
  <<: *nomad-agent

- name: mlc-client
  <<: *nomad-agent

provisioner:
  name: ansible
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
