---

- name: Converge
  hosts: standalone

  vars:
    server_enabled: true
    client_enabled: true
    cni_download: true
    cni_enabled: true
    plugin_podman_download: true
    plugin_podman_enabled: false
    plugin_singularity_download: false
    plugin_singularity_enabled: false

  roles:
    - role: nomad
