---
  # Configure firewall
- name: configure firewall settings
  become: true
  notify:
  - reload_daemon
  - restart_firewalld
  firewalld:
    service: {{ application }}
    permanent: yes
    state: enabled
    port: "{{ item }}"
  loop:
    - 4646-4648/tcp
    - 20000-32000/tcp
    - 4648/udp

- name: disable SELinux (Required?)
  selinux:
    state: disabled

- name: flush handlers
  meta: flush_handlers
