# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow
---
name: Molecule

on:
  push:
    branches:
      - master
#    paths:
#      - "nomad/**"

jobs:

  nomad-molecule-tests:
    runs-on: ubuntu-latest

    container:
      image: quay.io/ansible/molecule:latest
      env:
        PY_COLORS: 1
        DOCKER_DISTRO: "centos:7"
        DOCKER_COMMAND: "/usr/sbin/init"

    services:
      docker:
        image: docker:dind
        env:
          DOCKER_TLS_CERTDIR: /certs
        ports:
          - 2376:2376

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: Run tests
        run: |
          cd nomad
          molecule test
