# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow
---
name: Molecule CI

on:
  push:
    branches:
      - master
#    paths:
#      - "nomad/*"

jobs:
  build:
    name: Test
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run molecule
        uses: docker://alpine:latest
        with:
          entrypoint: /usr/bin/env
          args:  ash -c "echo testing"
