# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow
---
name: Molecule CI

on:
  push:
    branches:
      - master
#    paths:
#      - "nomad/*"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: quay.io/ansible/molecule:latest
      env:
        PY_COLORS: 1
        DOCKER_HOST: "tcp://docker:2375"
        DOCKER_DISTRO: "centos:7"
        DOCKER_COMMAND: "/usr/sbin/init"

    services:
      docker:
        image: docker:dind
        ports:
          - 2375/tcp

    steps:

      - name: Checkout code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1

      - name: Run tests
        run: |
          cd nomad
          molecule test

#    name: Test
#    runs-on: ubuntu-18.04
#    steps:

#      - name: Checkout code
#        uses: actions/checkout@v1
#        with:
#          fetch-depth: 1

#      - name: Testing docker
#        uses: docker://alpine:latest
#        with:
#          entrypoint: /usr/bin/env
#          args:  ash -c "echo testing the pipeline"

#      - name: Run molecule tests
#        uses: docker://quay.io/ansible/molecule:latest
#        with:
#          args: cd nomad && molecule test
